version: '2.2'
services:

  postgresql:
    container_name: demo-postgresql
    image: postgres:9.6.14
    hostname: postgresql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: demo
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
#    volumes:
#      - wap-postgresql-data:/var/lib/postgresql/data
    mem_limit: 512m

  demo-back:
    container_name: demo-back
    build: demo-back
    image: demo-back
    ports:
      - 8001:8001
    environment:
      TZ: Europe/Moscow
#      SPRING_PROFILES_ACTIVE: docker
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8001/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      postgresql:
        condition: service_healthy


#volumes:
#  mysql-data: