version: '2.2'
services:


  postgresql:
    container_name: wap-postgresql
    image: postgres:9.6.14
    hostname: postgresql
    environment:
      POSTGRES_USER: wapuser
      POSTGRES_PASSWORD: wapuser
      POSTGRES_DB: wapdb
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - wap-postgresql-data:/var/lib/postgresql/data
    mem_limit: 512m

  matching-back:
    container_name: demo-back
    build: demo-back
    image: demo-back
    ports:
      - 8001:8001
    environment:
      TZ: Europe/Moscow
#      SPRING_PROFILES_ACTIVE: docker
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8001/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      postgresql:
        condition: service_healthy
      mysql:
        condition: service_healthy
      clickhouse:
        condition: service_started
      redis:
        condition: service_started
      kafka:
        condition: service_started
      vsftpd:
        condition: service_started
      syslog:
        condition: service_started
      mailhog:
        condition: service_started

  matching-calc:
    image: matching-calc
    container_name: matching-calc
    build: matching-calc
    ports:
      - 8003:8003
    environment:
      TZ: Europe/Moscow
      SPRING_PROFILES_ACTIVE: docker
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8003/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      matching-config:
        condition: service_healthy
      redis:
        condition: service_started
      kafka:
        condition: service_started
      syslog:
        condition: service_started



#volumes:
#  mysql-data: